import pathlib

from typing import Protocol, TypeVar, AsyncIterator, Iterator

T = TypeVar("T", covariant=True)

class SyncAsyncIterator(Protocol[T]):
    def __aiter__(self) -> AsyncIterator[T]: ...
    async def __anext__(self) -> T: ...
    def __iter__(self) -> Iterator[T]: ...
    def __next__(self) -> T: ...

class Entry(object): ...

class Dataset(object):
    def download_with_validation(self, dst_dir: pathlib.Path, limit: int = 0) -> None:
        """blocking call, using rust's async runtime"""
    def crawl(self) -> SyncAsyncIterator[Entry]:
        """return a stream that can be either sync or async iterator over `Entry`"""
    def id(self) -> str: ...
    def root_url(self) -> str: ...

def resolve(url: str, /) -> Dataset: ...
